// Automatically generated by astro-icon
// c5b308583f3e6ed9c3326bd0ba13af7d94feacb29fee41dbf559d5bbe21cb9d8

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-narrow-right"
		| "arrow-narrow-up"
		| "at"
		| "brand-astro"
		| "brand-gsap"
		| "brand-tailwind"
		| "calendarTime"
		| "chevron-down"
		| "code-circle"
		| "eye"
		| "globe"
		| "handWave"
		| "home"
		| "language"
		| "line-dotted"
		| "mail"
		| "message-circle"
		| "music-note"
		| "pause"
		| "play"
		| "thumbUp"
		| "user-search";
}