// Automatically generated by astro-icon
// 77de7da715daa8877f53623309046bb954ca418ec0dd09563978c3825850cad9

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-narrow-right"
		| "arrow-narrow-up"
		| "at"
		| "brand-astro"
		| "brand-gsap"
		| "brand-nextjs"
		| "brand-react"
		| "brand-tailwind"
		| "brand-typescript"
		| "calendarTime"
		| "chevron-down"
		| "code-circle"
		| "devices"
		| "download"
		| "eye"
		| "file-text"
		| "globe"
		| "handWave"
		| "home"
		| "language"
		| "line-dotted"
		| "mail"
		| "message-circle"
		| "mobiledata"
		| "music-note"
		| "pause"
		| "play"
		| "plug-connected"
		| "rocket"
		| "server-cog"
		| "thumbUp"
		| "user-search";
}