// Automatically generated by astro-icon
// db30cf870eb7b07922d978b0de0f2725cf2f703d601e56faa2945244e43c709f

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-narrow-up"
		| "calendarTime"
		| "eye"
		| "handWave"
		| "message-circle"
		| "music-note"
		| "pause"
		| "play"
		| "thumbUp";
}