[build]
  publish = "dist"
  command = "npm run build"

[[edge_functions]]
  path = "/netlify/functions"
  function = "spotifyHandler"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"