/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    works: Work;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: string;
  title: string;
  author: string;
  /**
   * Brief description of the project for previews
   */
  excerpt?: string | null;
  /**
   * Contenido detallado del proyecto con formato enriquecido
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishDate?: string | null;
  /**
   * Main project hero image
   */
  image: string | Media;
  /**
   * Optional hero video (plays instead of image)
   */
  heroVideo?: (string | null) | Media;
  /**
   * Color for project theming
   */
  accentColor?: string | null;
  /**
   * Navigation menu for the project page
   */
  postIndex?:
    | {
        label: string;
        /**
         * Anchor link (e.g., "#section-1")
         */
        anchor: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Build your project page using blocks
   */
  layout?:
    | (
        | {
            /**
             * Your role in the project
             */
            rol: string;
            status: 'done' | 'in progress' | 'on hold' | 'cancelled';
            /**
             * Project duration (e.g., "2 months", "2022-2023")
             */
            duration: string;
            /**
             * Project overview and description
             */
            overview: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Optional additional title (e.g., "2023 Team")
             */
            title?: string | null;
            /**
             * Team members and roles (HTML supported)
             */
            team?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'singlePostInfo';
          }
        | {
            /**
             * Category or context (e.g., "Context", "Process")
             */
            preTitle?: string | null;
            /**
             * Main section title
             */
            title: string;
            /**
             * Section content - supports rich text formatting
             */
            content: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'singlePostSection';
          }
        | {
            /**
             * Image or video file
             */
            mediaFile: string | Media;
            /**
             * Media description or caption (HTML supported)
             */
            caption?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Animation delay in seconds
             */
            delay?: number | null;
            /**
             * Show frame/border around media
             */
            frame?: boolean | null;
            /**
             * Layout style for this media block
             */
            layout?: ('single' | 'half' | 'two-columns') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'postMedia';
          }
        | {
            /**
             * Optional title for the gallery section
             */
            title?: string | null;
            /**
             * Optional subtitle for the gallery section
             */
            subtitle?: string | null;
            /**
             * Type of media in this gallery
             */
            mediaType?: ('videos' | 'images' | 'mixed') | null;
            items: {
              mediaFile: string | Media;
              /**
               * Title for this gallery item
               */
              title: string;
              /**
               * Description or subtitle for this item
               */
              subtitle?: string | null;
              id?: string | null;
            }[];
            /**
             * Number of columns in the gallery grid
             */
            columns?: ('1' | '2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'postGalleryGrid';
          }
        | {
            cards: {
              /**
               * YouTube video ID (e.g., "TjkRhh3Gh1U")
               */
              ytId: string;
              /**
               * Card title
               */
              title: string;
              /**
               * Card description
               */
              description: string;
              /**
               * Additional information items with icons
               */
              info?:
                | {
                    /**
                     * Icon for this info item
                     */
                    icon:
                      | 'calendarTime'
                      | 'thumbUp'
                      | 'eye'
                      | 'clock'
                      | 'user'
                      | 'star'
                      | 'heart'
                      | 'play'
                      | 'message-circle';
                    /**
                     * Info text (e.g., "Published on: 22-12-2023")
                     */
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'postCards';
          }
        | {
            /**
             * Optional title for the statistics section
             */
            title?: string | null;
            stats: {
              /**
               * Statistic label (e.g., "CGI Scenes in Total")
               */
              title: string;
              /**
               * Statistic value (e.g., "260", "40+", "95%")
               */
              amount: string;
              /**
               * Optional additional description
               */
              description?: string | null;
              id?: string | null;
            }[];
            /**
             * Layout style for statistics
             */
            layout?: ('grid' | 'row' | 'vertical') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            /**
             * Select the next project to showcase
             */
            nextProject?: (string | null) | Work;
            /**
             * Custom image for next project (overrides project image)
             */
            customImage?: (string | null) | Media;
            /**
             * Custom title (overrides project title)
             */
            customTitle?: string | null;
            /**
             * Custom description for the next project link
             */
            customDescription?: string | null;
            /**
             * Custom URL (if not linking to a project in the system)
             */
            customUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'postNextProject';
          }
        | {
            /**
             * Rich text content with full formatting support
             */
            content: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            textAlign?: ('left' | 'center' | 'right' | 'justify') | null;
            /**
             * Content width constraint
             */
            maxWidth?: ('default' | 'narrow' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
      )[]
    | null;
  /**
   * Canonical URL for SEO
   */
  canonical?: string | null;
  /**
   * URL slug for the project
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'works';
        value: string | Work;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  excerpt?: T;
  content?: T;
  publishDate?: T;
  image?: T;
  heroVideo?: T;
  accentColor?: T;
  postIndex?:
    | T
    | {
        label?: T;
        anchor?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        singlePostInfo?:
          | T
          | {
              rol?: T;
              status?: T;
              duration?: T;
              overview?: T;
              title?: T;
              team?: T;
              id?: T;
              blockName?: T;
            };
        singlePostSection?:
          | T
          | {
              preTitle?: T;
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        postMedia?:
          | T
          | {
              mediaFile?: T;
              caption?: T;
              delay?: T;
              frame?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        postGalleryGrid?:
          | T
          | {
              title?: T;
              subtitle?: T;
              mediaType?: T;
              items?:
                | T
                | {
                    mediaFile?: T;
                    title?: T;
                    subtitle?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        postCards?:
          | T
          | {
              cards?:
                | T
                | {
                    ytId?: T;
                    title?: T;
                    description?: T;
                    info?:
                      | T
                      | {
                          icon?: T;
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              title?: T;
              stats?:
                | T
                | {
                    title?: T;
                    amount?: T;
                    description?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        postNextProject?:
          | T
          | {
              nextProject?: T;
              customImage?: T;
              customTitle?: T;
              customDescription?: T;
              customUrl?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              textAlign?: T;
              maxWidth?: T;
              id?: T;
              blockName?: T;
            };
      };
  canonical?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}